title: Omnipresent Supergalactic Oneness
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Omnipresent Supergalactic Oneness

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: UA-86563829-3

sass:
    style: compressed